name: Run Tests
on: [push]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.7
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.x
      - name: Build and run tests
        if: success()
        run: |
          gem install bundler
          bundle install
          bundle exec rake test
      - name: Build and run tests
        if: success()
        run: |
          ruby cli.rb test-images
